### PR TITLE
update ci.yml to test Nim 2.2; also test gcc-14

### PR DESCRIPTION
**Pull request by narimiran**

### CODE REVIEW

**Comment by narimiran** [comment]
While everything is now green, on previous runs `macos-arm64` CIs sometimes get stuck for multiple hours!?!

Adding a timeout, for this to not happen in future.

**Comment by tersec** [comment]
> While everything is now green, on previous runs `macos-arm64` CIs sometimes get stuck for multiple hours!?!
> 
> Adding a timeout, for this to not happen in future.

Tried rerunning `CI / macos-amd64 (Nim version-2-0) (pull_request)` with same result, which is odd

**Comment by arnetheduck** [comment]
same in https://github.com/status-im/nim-web3/pull/161 - cc @narimiran can you rerun with older vesion-2-0 commits until we find a working one?

**Comment by arnetheduck** [comment]
oddly, https://github.com/status-im/nim-web3/actions/runs/11073578054/job/30770415721 succeeded 2 days ago

**Comment by arnetheduck** [comment]
ok, looks like 1.6 crashes on compilation now which is probably due to the new nim-eth types - gonna merge this PR as well

**Comment by narimiran** [comment]
> oddly, https://github.com/status-im/nim-web3/actions/runs/11073578054/job/30770415721 succeeded 2 days ago

It's not that it fails 100% of time. (But from the number of failing CIs attempt, it looks like failure rate is 80+%)

**Pull request merged**
