### PR TITLE
fix: allow Bool input/output types for contracts

### PR DESCRIPTION
**Pull request by emizzle**
Contracts created with the `contract` macro and having a method with a `Bool` input/output type were failing to compile. Example:
```
contract(MyContract):
  proc enableTransfers(
    transfersEnabled: Bool
  )
```
Fails with:
```
Error: type mismatch: got <type Bool>
but expected one of:
proc unknownType()
  first type mismatch at position: 1
  extra argument given

expression: unknownType(Bool)
```
This fix enables translating `Bool` type signatures to solidity’s `bool` type.

### CODE REVIEW

**Comment by emizzle** [comment]
@arnetheduck test added for encoding/decoding `Bool`.

**Comment by emizzle** [comment]
One test seems to have been cancelled, and it doesn't appear that I have permissions to restart the CI jobs.

**Comment by emizzle** [comment]
@arnetheduck @zah, any thoughts on this PR? We have [an open PR in `nim-status`](https://github.com/status-im/nim-status/pull/299) relying on this.

**Comment by zah** [comment]
Why do we need `Bool` as a separate distinct type instead of relying on the built-in Nim `bool` type?

**Comment by emizzle** [comment]
That's a really great question, and I'd love to know more if you have any ideas. The `contract` macro had this type already included, so I made it work with encoding/decoding, but as to why it was included in the first place, I'm not so sure.

**Comment by arnetheduck** [comment]
presumably to have a place to check for any edge-case differences between nim and web3? there are usually small differences in explicit or implicit semantics (like what to do with values that are not 0 or 1) with `bool` types in any language

**Review by arnetheduck — APPROVED** [review]

**Comment by arnetheduck** [comment]
examples: exact roundtripping, inspection of semi-invalid values like 2, hashing etc - too clever type manipulations (specially in generic serialization frameworks) tend to lose information like this

**Pull request merged**
